/** Treatment name options for Create Treatment Metadata combobox (user can also type custom). */
export const TREATMENT_NAME_OPTIONS = [
  "Botox (Wrinkle Relaxers)",
  "Dermal Fillers (Hyaluronic Acid, Juvederm, Restylane)",
  "PRP (Platelet-Rich Plasma) Injections",
  "Kybella / Deoxycholic Acid (Fat-dissolving injections)",
  "Mesotherapy",
  "Lip Fillers",
  "Cheek / Jawline Contouring",
  "Chemical Peels (Glycolic, TCA, Salicylic)",
  "Microdermabrasion",
  "Microneedling / Collagen Induction Therapy",
  "Laser Skin Resurfacing (CO2, Erbium, Fractional)",
  "Skin Tightening (RF, Ultrasound, HIFU)",
  "LED / Phototherapy",
  "Scar / Stretch Mark Treatment",
  "Acne / Acne Scar Treatment",
  "CoolSculpting / Cryolipolysis",
  "Laser Lipolysis",
  "Radiofrequency Body Contouring",
  "Ultrasound Cavitation / Fat Reduction",
  "Cellulite Treatment",
  "Skin Firming & Tightening Treatments",
  "PRP for Hair Loss",
  "Scalp Micropigmentation",
  "Laser Hair Removal",
  "Hair Restoration / Transplant",
  "Hydrafacial / Aqua Facial",
  "Oxygen Facial",
  "Vampire Facial (PRP + Microneedling)",
  "Facials with Custom Serums",
  "Facial Rejuvenation / Anti-Aging Treatments",
  "IPL Photofacial / Skin Rejuvenation",
  "Tattoo Removal",
  "Pigmentation / Melasma Treatment",
  "Vascular / Vein Treatment",
  "Teeth Whitening",
  "Smile Design",
  "Orthodontic Aligners (Clear Aligners)",
  "Liposuction",
  "Thread Lift",
  "Eyelid Surgery (Blepharoplasty)",
  "Rhinoplasty",
  "Chin / Jaw Augmentation",
  "Breast Augmentation / Reduction",
  "Minor Cosmetic Surgeries",
  "Vitamin IV Therapy",
  "Hydration IV Drip",
  "Detox IV Drip",
  "Glutathione IV (Skin Brightening)",
  "Immunity Boost IV Drip",
  "NAD+ IV Therapy",
  "Energy / Performance IV Drip",
  "Anti-Aging IV Drip",
  "Cryotherapy / Cryo Facials",
  "Hormone Therapy (anti-aging)",
  "Body Wraps / Detox Treatments",
  "PRP for Joints / Sports Recovery",
  "Weight Management Injections (e.g., L-Carnitine)",
  "Non-surgical Hair & Nail Treatments",
];
