#!/bin/bash

OUTPUT="5th-deployment.sql"

echo "Generating complete database export with IDENTITY constraints..."

# Export with all identity information preserved
pg_dump "$DATABASE_URL" \
  --clean \
  --if-exists \
  --no-owner \
  --no-privileges \
  --column-inserts \
  --file="$OUTPUT"

# Now add explicit IDENTITY constraint information
echo "" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "-- =============================================" >> "$OUTPUT"
echo "-- IDENTITY/GENERATED CONSTRAINTS" >> "$OUTPUT"
echo "-- =============================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Get all tables with serial/identity columns
psql "$DATABASE_URL" -t -c "
SELECT 
    'ALTER TABLE ' || n.nspname || '.' || c.relname || 
    ' ALTER COLUMN ' || a.attname || 
    ' ADD GENERATED BY DEFAULT AS IDENTITY;'
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid
JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
WHERE c.relkind = 'r'
  AND n.nspname = 'public'
  AND a.attnum > 0
  AND NOT a.attisdropped
  AND d.adsrc LIKE '%nextval%'
ORDER BY c.relname, a.attnum;
" >> "$OUTPUT"

echo "Export completed!"

