import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Calendar, Heart, Pill, FileText, Clock, AlertCircle, MessageSquare, User, MapPin, Video, X, Download } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useAuth } from "@/hooks/use-auth";
import { useCurrency } from "@/hooks/use-currency";
import { useState, useEffect, useRef } from "react";
import { format } from "date-fns";
import { useToast } from "@/hooks/use-toast";
import AIChatbot from "@/components/ai-chatbot";
import jsPDF from 'jspdf';
import { getActiveSubdomain } from "@/lib/subdomain-utils";

const statusColors = {
  scheduled: "#4A7DFF",
  completed: "#6CFFEB",
  cancelled: "#162B61",
  no_show: "#9B9EAF",
};

export function PatientDashboard() {
  const { user } = useAuth();
  const { currencySymbol } = useCurrency();
  const queryClient = useQueryClient();
  const { toast } = useToast();
  
  // Track previous counts for auto-refresh notifications
  const prevAppointmentsCountRef = useRef<number>(0);
  const prevPrescriptionsCountRef = useRef<number>(0);
  const prevPendingResultsCountRef = useRef<number>(0);
  
  const [isChatbotOpen, setIsChatbotOpen] = useState(false);
  const [isPrescriptionsPopupOpen, setIsPrescriptionsPopupOpen] = useState(false);
  const [isLabResultsPopupOpen, setIsLabResultsPopupOpen] = useState(false);
  const [selectedLabResult, setSelectedLabResult] = useState(null);
  const [isLabResultDetailOpen, setIsLabResultDetailOpen] = useState(false);
  const [isHealthRecordsPopupOpen, setIsHealthRecordsPopupOpen] = useState(false);
  const [isPendingResultsPopupOpen, setIsPendingResultsPopupOpen] = useState(false);

  // PDF Generation Function
  const generateLabResultPDF = (labResult: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(74, 125, 255); // Blue color
    doc.text('emrSoft System', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Laboratory Test Prescription (RESIDENT PHYSICIAN M.D)', 105, 30, { align: 'center' });
    
    // Clinic Information
    doc.setFontSize(10);
    doc.text('EmrSoft Health Clinic', 105, 40, { align: 'center' });
    doc.text('Unit 2 Drayton Court, Solihull', 105, 47, { align: 'center' });
    doc.text('B90 4NG, UK', 105, 54, { align: 'center' });
    doc.text('+92 33***********', 105, 61, { align: 'center' });
    
    // Physician Information
    doc.setFontSize(14);
    doc.setTextColor(74, 125, 255);
    doc.text('Physician Information', 20, 80);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text('Name: Dr. Dr. John Smith', 20, 90);
    doc.text('Main Specialization: General & Primary Care', 20, 97);
    doc.text('Sub-Specialization: General Practitioner (GP) / Family Physician', 20, 104);
    doc.text('Priority: routine', 20, 111);
    
    // Patient Information
    doc.setFontSize(14);
    doc.setTextColor(74, 125, 255);
    doc.text('Patient Information', 120, 80);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Name: ${user?.firstName} ${user?.lastName}`, 120, 90);
    doc.text('Patient ID: 25', 120, 97);
    doc.text(`Date: ${labResult.testDate ? new Date(labResult.testDate).toLocaleDateString() : 'Sep 25, 2025'}`, 120, 104);
    doc.text(`Time: ${labResult.testTime || '13:43'}`, 120, 111);
    
    // Laboratory Test Prescription Section
    doc.setFontSize(14);
    doc.setTextColor(74, 125, 255);
    doc.text('℞ Laboratory Test Prescription', 20, 130);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Test ID: ${labResult.testId || labResult.id || 'LAB175877489700K5Q18'}`, 20, 145);
    doc.text(`Test Type: ${labResult.testType || labResult.type || 'Vitamin D, Thyroid Function Tests'}`, 20, 152);
    doc.text(`Ordered Date: ${labResult.testDate ? new Date(labResult.testDate).toLocaleDateString() : 'Sep 25, 2025'} ${labResult.testTime || '09:34'}`, 20, 159);
    doc.text(`Status: ${labResult.status || 'PENDING'}`, 20, 166);
    
    // Clinical Notes
    doc.setFontSize(12);
    doc.setTextColor(74, 125, 255);
    doc.text('Clinical Notes:', 20, 180);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(labResult.notes || 'none', 20, 190);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by emrSoft System', 105, 280, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 105, 285, { align: 'center' });
    
    // Save the PDF
    const fileName = `Lab_Result_${user?.firstName}_${user?.lastName}_${labResult.testId || labResult.id || 'LAB175877489700K5Q18'}.pdf`;
    doc.save(fileName);
  };
  
  const { data: appointmentsData, isLoading: appointmentsLoading, error: appointmentsError } = useQuery({
    queryKey: ["/api/appointments"],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch('/api/appointments', {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch appointments: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user, // Enable for any authenticated user
    staleTime: 0,
    refetchOnMount: true,
    // Auto-refresh for patient role: poll every 10 seconds to get new appointments
    refetchInterval: user?.role === "patient" ? 10000 : false, // 10 seconds = 10000ms
    refetchIntervalInBackground: user?.role === "patient", // Continue polling even when tab is in background
  });


  // Ensure we have an array for appointments data
  const safeAppointmentsData = Array.isArray(appointmentsData) ? appointmentsData : [];


  const { data: prescriptionsData } = useQuery({
    queryKey: ["/api/patients/my-prescriptions", user?.id],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch('/api/patients/my-prescriptions', {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch prescriptions: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user && user.role === 'patient',
    staleTime: 0,
    refetchOnMount: true,
    // Auto-refresh for patient role: poll every 10 seconds to get new prescriptions
    refetchInterval: user?.role === "patient" ? 10000 : false, // 10 seconds = 10000ms
    refetchIntervalInBackground: user?.role === "patient", // Continue polling even when tab is in background
  });

  const { data: labResultsData } = useQuery({
    queryKey: ["/api/mobile/patient/lab-results", user?.id],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch('/api/mobile/patient/lab-results', {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch lab results: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user && user.role === 'patient',
    staleTime: 0,
    refetchOnMount: true,
  });

  // Health Score query
  const { data: healthScoreData, isLoading: healthScoreLoading } = useQuery({
    queryKey: ["/api/patients/health-score", user?.id],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch('/api/patients/health-score', {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch health score: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user && user.role === 'patient',
    staleTime: 5 * 60 * 1000, // Cache for 5 minutes since health score calculation is expensive
    refetchOnMount: true,
  });

  // Fetch patients data to get current patient ID - MUST come first before medical imaging query
  const { data: patients = [], isLoading: patientsLoading } = useQuery({
    queryKey: ["/api/patients"],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch('/api/patients?isActive=true', {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch patients: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user && user.role === 'patient',
    staleTime: 0,
    refetchOnMount: true,
  });

  // Find current patient ID based on user email (same logic as lab results)
  const currentPatient = patients.find((patient: any) => 
    patient.email && user?.email && patient.email.toLowerCase() === user.email.toLowerCase()
  ) || patients.find((patient: any) => 
    patient.firstName && user?.firstName && patient.lastName && user?.lastName &&
    patient.firstName.toLowerCase() === user.firstName.toLowerCase() && 
    patient.lastName.toLowerCase() === user.lastName.toLowerCase()
  );

  const currentPatientId = currentPatient?.id;

  // Fetch pending results for patient role
  const { data: pendingResultsData } = useQuery({
    queryKey: ["/api/patients/pending-results", currentPatientId],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch(`/api/patients/${currentPatientId}/pending-results`, {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch pending results: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user && user.role === 'patient' && !!currentPatientId,
    staleTime: 0,
    refetchOnMount: true,
    // Auto-refresh for patient role: poll every 10 seconds to get new pending results
    refetchInterval: user?.role === "patient" && currentPatientId ? 10000 : false, // 10 seconds = 10000ms
    refetchIntervalInBackground: user?.role === "patient", // Continue polling even when tab is in background
  });

  // Medical Imaging data query for patient - now dynamic based on current patient
  const { data: medicalImagingData } = useQuery({
    queryKey: ["/api/patients", currentPatientId, "medical-imaging"],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch(`/api/patients/${currentPatientId}/medical-imaging`, {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch medical imaging: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user && user.role === 'patient' && !!currentPatientId && patients.length > 0,
    staleTime: 0,
    refetchOnMount: true,
  });

  const { data: doctorsData } = useQuery({
    queryKey: ["/api/medical-staff"],
    queryFn: async () => {
      const token = localStorage.getItem('auth_token');
      const subdomain = localStorage.getItem('user_subdomain') || getActiveSubdomain();
      const headers: Record<string, string> = {
        'X-Tenant-Subdomain': subdomain
      };
      
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch('/api/medical-staff', {
        headers,
        credentials: 'include',
      });
      
      if (!response.ok) {
        throw new Error(`Failed to fetch medical staff: ${response.status}`);
      }
      
      return response.json();
    },
    enabled: !!user,
  });

  // Helper functions
  const getDoctorSpecialtyData = (providerId: number) => {
    const doctorsResponse = doctorsData as any;
    if (!doctorsResponse?.staff || !Array.isArray(doctorsResponse.staff))
      return { name: "", category: "", subSpecialty: "" };
    const provider = doctorsResponse.staff.find((u: any) => u.id === providerId);
    return provider
      ? {
          name: `${provider.firstName} ${provider.lastName}`,
          category: provider.medicalSpecialtyCategory || "",
          subSpecialty: provider.subSpecialty || "",
        }
      : { name: "", category: "", subSpecialty: "" };
  };

  const formatTime = (timeString: string) => {
    try {
      const date = new Date(timeString);
      return format(date, "h:mm a");
    } catch {
      return "Invalid time";
    }
  };

  const formatDate = (timeString: string) => {
    try {
      const date = new Date(timeString);
      return format(date, "EEEE, MMMM d, yyyy");
    } catch {
      return "Invalid date";
    }
  };

  // Get upcoming appointments for patient users
  const getUpcomingAppointments = () => {
    const now = new Date();
    
    // For patient users, filter appointments by current patient's database ID
    // For non-patient users, show all appointments
    const patientAppointments = safeAppointmentsData.filter((appointment: any) => {
      // If user is a patient, only show their appointments
      if (user?.role === 'patient') {
        // appointment.patientId is the integer database ID from the appointments table
        // currentPatient.id is the integer database ID from the patients table
        const isForCurrentPatient = currentPatient && appointment.patientId === currentPatient.id;
        
        const appointmentDate = new Date(appointment.scheduledAt);
        const isUpcoming = appointmentDate >= now; // Include today's appointments
        
        return isForCurrentPatient && isUpcoming;
      }
      
      // For non-patient users, show all upcoming appointments
      const appointmentDate = new Date(appointment.scheduledAt);
      return appointmentDate >= now;
    });

    // Sort by date (earliest first)
    const sortedAppointments = patientAppointments.sort((a: any, b: any) => {
      return new Date(a.scheduledAt).getTime() - new Date(b.scheduledAt).getTime();
    });

    return {
      appointments: sortedAppointments,
      count: sortedAppointments.length,
      nextAppointment: sortedAppointments[0] || null,
      remainingAppointments: sortedAppointments.slice(1),
    };
  };

  const upcomingAppointmentsData = getUpcomingAppointments();

  // Use the filtered appointment data from getUpcomingAppointments
  const nextAppointment = upcomingAppointmentsData.nextAppointment;
  const prescriptions = (prescriptionsData as any)?.prescriptions || [];
  const totalPrescriptions = (prescriptionsData as any)?.totalCount || 0;
  const patientId = (prescriptionsData as any)?.patientId || (appointmentsData as any)?.patientId;

  // Calculate total pending results count
  const totalPendingCount = (pendingResultsData?.totalCount || 0);

  // Notify patient when new appointments are detected
  useEffect(() => {
    if (user?.role === "patient" && upcomingAppointmentsData) {
      const currentCount = upcomingAppointmentsData.count || 0;
      const previousCount = prevAppointmentsCountRef.current;

      // Only show notification if count increased (new appointments added)
      if (previousCount > 0 && currentCount > previousCount) {
        const newAppointmentsCount = currentCount - previousCount;
        toast({
          title: "New Appointment Available",
          description: `${newAppointmentsCount} new appointment${newAppointmentsCount > 1 ? 's' : ''} ${newAppointmentsCount > 1 ? 'have' : 'has'} been scheduled.`,
          variant: "default",
        });
      }

      // Update the ref with current count
      prevAppointmentsCountRef.current = currentCount;
    }
  }, [upcomingAppointmentsData, user?.role, toast]);

  // Notify patient when new prescriptions are detected
  useEffect(() => {
    if (user?.role === "patient" && totalPrescriptions !== undefined) {
      const currentCount = totalPrescriptions;
      const previousCount = prevPrescriptionsCountRef.current;

      // Only show notification if count increased (new prescriptions added)
      if (previousCount > 0 && currentCount > previousCount) {
        const newPrescriptionsCount = currentCount - previousCount;
        toast({
          title: "New Prescription Available",
          description: `${newPrescriptionsCount} new prescription${newPrescriptionsCount > 1 ? 's' : ''} ${newPrescriptionsCount > 1 ? 'have' : 'has'} been added.`,
          variant: "default",
        });
      }

      // Update the ref with current count
      prevPrescriptionsCountRef.current = currentCount;
    }
  }, [totalPrescriptions, user?.role, toast]);

  // Notify patient when new pending results are detected
  useEffect(() => {
    if (user?.role === "patient" && totalPendingCount !== undefined) {
      const currentCount = totalPendingCount;
      const previousCount = prevPendingResultsCountRef.current;

      // Only show notification if count increased (new pending results added)
      if (previousCount > 0 && currentCount > previousCount) {
        const newPendingCount = currentCount - previousCount;
        toast({
          title: "New Pending Results Available",
          description: `${newPendingCount} new pending result${newPendingCount > 1 ? 's' : ''} ${newPendingCount > 1 ? 'have' : 'has'} been added.`,
          variant: "default",
        });
      }

      // Update the ref with current count
      prevPendingResultsCountRef.current = currentCount;
    }
  }, [totalPendingCount, user?.role, toast]);

  const patientCards = [
    {
      title: "Next Appointment",
      value: upcomingAppointmentsData.count > 0 ? new Date(nextAppointment.scheduledAt).toLocaleDateString() : "0 Appointments",
      description: nextAppointment ? nextAppointment.provider : "Schedule one today",
      icon: Calendar,
      href: "/appointments",
      color: "bg-blue-100 text-blue-800"
    },
    {
      title: "Active Prescriptions",
      value: totalPrescriptions.toString(),
      description: patientId ? `Patient ID: ${patientId}` : "Current medications",
      icon: Pill,
      href: "/prescriptions",
      color: "bg-green-100 text-green-800"
    },
    {
      title: "Health Score",
      value: healthScoreLoading ? "..." : healthScoreData ? `${healthScoreData.score}%` : "N/A",
      description: healthScoreData ? `${healthScoreData.category} - Based on ${healthScoreData.totalRecords} records` : "Based on recent vitals",
      icon: Heart,
      href: "/health-summary",
      color: healthScoreData ? 
        (healthScoreData.score >= 85 ? "bg-green-100 text-green-800" :
         healthScoreData.score >= 70 ? "bg-blue-100 text-blue-800" :
         healthScoreData.score >= 50 ? "bg-yellow-100 text-yellow-800" :
         "bg-red-100 text-red-800") : 
        "bg-purple-100 text-purple-800"
    },
    {
      title: "Pending Results",
      value: totalPendingCount.toString(),
      description: "Lab test results",
      icon: FileText,
      href: "#",
      color: "bg-orange-100 text-orange-800",
      isPendingResults: true
    }
  ];

  const quickActions = [
    { title: "Book Appointment", description: "Schedule with your healthcare provider", icon: Calendar, href: "/appointments" },
    { title: "View Prescriptions", description: "Check your current medications", icon: Pill, href: "/prescriptions", isPopupAction: true },
    { title: "Lab Results", description: "View your test results", icon: FileText, href: "/lab-results", isPopupAction: true },
    { title: "Medical Imaging", description: "Access your medical history", icon: Heart, href: "/medical-records", isPopupAction: true }
  ];

  // Handle popup actions for patient users
  const handlePopupAccess = (action: any) => {
    if (action.title === "View Prescriptions" && user?.role === "patient") {
      setIsPrescriptionsPopupOpen(true);
    } else if (action.title === "Lab Results" && user?.role === "patient") {
      setIsLabResultsPopupOpen(true);
    } else if (action.title === "Medical Imaging" && user?.role === "patient") {
      setIsHealthRecordsPopupOpen(true);
      // Invalidate medical imaging query to fetch fresh data when popup opens
      if (currentPatientId) {
        queryClient.invalidateQueries({ 
          queryKey: ["/api/patients", currentPatientId, "medical-imaging"] 
        });
      }
    } else {
      // For non-patient users or other actions, use normal navigation
      window.location.href = action.href;
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">
          Welcome back, {user?.firstName || "Patient"}
        </h1>
        <p className="text-neutral-600">
          Your personal health dashboard and medical information
        </p>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {patientCards.map((card) => (
          card.isPendingResults ? (
            <Card key={card.title} className="hover:shadow-lg transition-shadow cursor-pointer" onClick={() => setIsPendingResultsPopupOpen(true)}>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">{card.title}</CardTitle>
                <div className={`p-2 rounded-full ${card.color}`}>
                  <card.icon className="h-4 w-4" />
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{card.value}</div>
                <p className="text-xs text-neutral-500">{card.description}</p>
              </CardContent>
            </Card>
          ) : (
            <Link key={card.title} href={card.href}>
              <Card className="hover:shadow-lg transition-shadow cursor-pointer">
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">{card.title}</CardTitle>
                  <div className={`p-2 rounded-full ${card.color}`}>
                    <card.icon className="h-4 w-4" />
                  </div>
                </CardHeader>
                <CardContent>
                  {card.title === "Next Appointment" && nextAppointment ? (
                    <div>
                      <div className={user?.role === "patient" ? "text-lg font-bold" : "text-2xl font-bold"}>
                        {user?.role === "patient" ? (() => {
                          const date = new Date(nextAppointment.scheduledAt);
                          const day = date.getDate();
                          const month = date.toLocaleDateString('en-GB', { month: 'long' });
                          const year = date.getFullYear();
                          const suffix = day === 1 || day === 21 || day === 31 ? 'st' : 
                                        day === 2 || day === 22 ? 'nd' : 
                                        day === 3 || day === 23 ? 'rd' : 'th';
                          return `${day}${suffix} ${month}, ${year}`;
                        })() : new Date(nextAppointment.scheduledAt).toLocaleDateString()}
                      </div>
                      <div className="text-sm text-gray-500 mt-1">{new Date(nextAppointment.scheduledAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: true })}</div>
                    </div>
                  ) : (
                    <div className="text-2xl font-bold">{card.value}</div>
                  )}
                  <p className="text-xs text-neutral-500">{card.description}</p>
                </CardContent>
              </Card>
            </Link>
          )
        ))}
      </div>

      {/* Quick Actions */}
      <div>
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Quick Actions</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {quickActions.map((action) => (
            <Card key={action.title} className="hover:shadow-md transition-shadow">
              <CardHeader>
                <div className="flex items-center space-x-3">
                  <action.icon className="h-8 w-8 text-primary" />
                  <div>
                    <CardTitle className="text-base">{action.title}</CardTitle>
                    <CardDescription className="text-sm">{action.description}</CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                {action.isPopupAction && user?.role === "patient" ? (
                  <Button 
                    className="w-full" 
                    variant="outline"
                    onClick={() => handlePopupAccess(action)}
                  >
                    Access
                  </Button>
                ) : (
                  <Link href={action.href}>
                    <Button className="w-full" variant="outline">Access</Button>
                  </Link>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Patient-specific content */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Upcoming Appointments</CardTitle>
            <CardDescription>Your scheduled healthcare visits</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {upcomingAppointmentsData.count === 0 ? (
                <div className="text-center py-4">
                  <Calendar className="h-12 w-12 text-neutral-300 mx-auto mb-2" />
                  <p className="text-neutral-500">No upcoming appointments</p>
                  <Button className="mt-2" size="sm" asChild>
                    <Link href="/appointments">Book Appointment</Link>
                  </Button>
                </div>
              ) : (
                <div className="space-y-3">
                  {upcomingAppointmentsData.appointments.slice(0, 3).map((appointment: any) => {
                    const doctorInfo = getDoctorSpecialtyData(appointment.providerId);
                    return (
                      <div key={appointment.id} className="flex items-start space-x-3 p-3 bg-gray-50 rounded-lg">
                        <Calendar className="h-5 w-5 text-primary mt-1" />
                        <div className="flex-1">
                          <p className="font-medium text-sm">{appointment.title}</p>
                          <p className="text-xs text-neutral-600">
                            {doctorInfo.name && `Dr. ${doctorInfo.name} - `}
                            {formatDate(appointment.scheduledAt)}
                          </p>
                          <p className="text-xs text-neutral-500">{appointment.location || 'Location TBD'}</p>
                        </div>
                        <Badge variant={appointment.status === 'scheduled' ? 'default' : 'secondary'}>
                          {appointment.status}
                        </Badge>
                      </div>
                    );
                  })}
                  {upcomingAppointmentsData.count > 3 && (
                    <Button variant="outline" size="sm" className="w-full" asChild>
                      <Link href="/appointments">View All {upcomingAppointmentsData.count} Appointments</Link>
                    </Button>
                  )}
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Health Reminders</CardTitle>
            <CardDescription>Important health notices</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {(() => {
                const generateHealthReminders = () => {
                  const reminders: any[] = [];
                  const now = new Date();
                  
                  // Medication Reminders from Active Prescriptions
                  if (prescriptions && prescriptions.length > 0) {
                    prescriptions.forEach((prescription: any) => {
                      // Check if prescription is currently active
                      const issuedDate = prescription.issuedDate ? new Date(prescription.issuedDate) : null;
                      const duration = prescription.duration;
                      
                      if (issuedDate && duration) {
                        // Parse duration (assuming format like "7 days", "2 weeks", "1 month")
                        const durationMatch = duration.match(/(\d+)\s*(day|week|month)s?/i);
                        if (durationMatch) {
                          const amount = parseInt(durationMatch[1]);
                          const unit = durationMatch[2].toLowerCase();
                          
                          let endDate = new Date(issuedDate);
                          if (unit === 'day') {
                            endDate.setDate(endDate.getDate() + amount);
                          } else if (unit === 'week') {
                            endDate.setDate(endDate.getDate() + (amount * 7));
                          } else if (unit === 'month') {
                            endDate.setMonth(endDate.getMonth() + amount);
                          }
                          
                          // If prescription is still active, add reminder
                          if (now <= endDate) {
                            const daysRemaining = Math.ceil((endDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
                            
                            let timeframe = "Active";
                            let urgency = "blue";
                            
                            if (daysRemaining <= 3) {
                              timeframe = "Ending Soon";
                              urgency = "red";
                            } else if (daysRemaining <= 7) {
                              timeframe = "This Week";
                              urgency = "orange";
                            }
                            
                            reminders.push({
                              type: 'medication',
                              title: 'Medication Reminder',
                              description: `Take ${prescription.medicationName} - ${prescription.frequency}`,
                              timeframe,
                              urgency,
                              priority: daysRemaining <= 3 ? 1 : daysRemaining <= 7 ? 2 : 3
                            });
                          }
                        }
                      }
                    });
                  }
                  
                  // Next Appointment Reminder (only show the latest/earliest one)
                  if (upcomingAppointmentsData.appointments && upcomingAppointmentsData.appointments.length > 0) {
                    // Filter appointments within 7 days and sort by date to get the earliest one
                    const upcomingAppointments = upcomingAppointmentsData.appointments
                      .map((appointment: any) => ({
                        ...appointment,
                        appointmentDate: new Date(appointment.scheduledAt),
                        daysUntil: Math.ceil((new Date(appointment.scheduledAt).getTime() - now.getTime()) / (1000 * 60 * 60 * 24))
                      }))
                      .filter((appointment: any) => appointment.daysUntil >= 0 && appointment.daysUntil <= 7)
                      .sort((a: any, b: any) => a.appointmentDate.getTime() - b.appointmentDate.getTime());
                    
                    if (upcomingAppointments.length > 0) {
                      const nextAppointment = upcomingAppointments[0]; // Get the earliest appointment
                      const daysUntil = nextAppointment.daysUntil;
                      
                      let timeframe = "This Week";
                      let urgency = "green";
                      
                      if (daysUntil === 0) {
                        timeframe = "Today";
                        urgency = "blue";
                      } else if (daysUntil === 1) {
                        timeframe = "Tomorrow";
                        urgency = "blue";
                      } else if (daysUntil <= 3) {
                        timeframe = `In ${daysUntil} days`;
                        urgency = "orange";
                      }
                      
                      const doctorInfo = getDoctorSpecialtyData(nextAppointment.providerId);
                      
                      reminders.push({
                        type: 'appointment',
                        title: 'Next Appointment',
                        description: `${nextAppointment.title}${doctorInfo.name ? ` with ${doctorInfo.name}` : ''}`,
                        timeframe,
                        urgency,
                        priority: daysUntil === 0 ? 1 : daysUntil <= 1 ? 2 : 3
                      });
                    }
                  }
                  
                  // Pending Lab Results Reminders
                  if (totalPendingCount > 0) {
                    reminders.push({
                      type: 'lab_results',
                      title: 'Lab Results Available',
                      description: `${totalPendingCount} result${totalPendingCount > 1 ? 's' : ''} pending review`,
                      timeframe: 'New',
                      urgency: 'orange',
                      priority: 2
                    });
                  }
                  
                  // Health Check Reminders (Based on last appointment)
                  if (upcomingAppointmentsData.appointments.length === 0) {
                    // No upcoming appointments scheduled
                    reminders.push({
                      type: 'health_check',
                      title: 'Schedule Health Check',
                      description: 'Regular checkup recommended',
                      timeframe: 'Recommended',
                      urgency: 'green',
                      priority: 4
                    });
                  }
                  
                  // Overdue Lab Results Check (if no recent lab data)
                  if ((!labResultsData || labResultsData.length === 0) && totalPendingCount === 0) {
                    reminders.push({
                      type: 'lab_check',
                      title: 'Lab Work Due',
                      description: 'Consider scheduling routine lab work',
                      timeframe: 'Suggested',
                      urgency: 'green',
                      priority: 5
                    });
                  }
                  
                  // Sort reminders by priority (1 = highest, 5 = lowest)
                  return reminders.sort((a, b) => a.priority - b.priority).slice(0, 5); // Show max 5 reminders
                };
                
                const reminderColors = {
                  blue: { border: 'border-blue-200', bg: 'bg-blue-50', icon: 'text-blue-600', badge: 'bg-blue-100 text-blue-800' },
                  green: { border: 'border-green-200', bg: 'bg-green-50', icon: 'text-green-600', badge: 'bg-green-100 text-green-800' },
                  orange: { border: 'border-orange-200', bg: 'bg-orange-50', icon: 'text-orange-600', badge: 'bg-orange-100 text-orange-800' },
                  red: { border: 'border-red-200', bg: 'bg-red-50', icon: 'text-red-600', badge: 'bg-red-100 text-red-800' }
                };
                
                const reminderIcons = {
                  medication: Clock,
                  appointment: Calendar,
                  lab_results: FileText,
                  health_check: Heart,
                  lab_check: AlertCircle
                };
                
                const healthReminders = generateHealthReminders();
                
                if (healthReminders.length === 0) {
                  return (
                    <div className="text-center py-6">
                      <Heart className="h-12 w-12 text-green-300 mx-auto mb-2" />
                      <p className="text-neutral-500">All caught up! No health reminders at this time.</p>
                      <p className="text-sm text-neutral-400 mt-1">Keep up the great work with your health.</p>
                    </div>
                  );
                }
                
                return healthReminders.map((reminder, index) => {
                  const colors = reminderColors[reminder.urgency as keyof typeof reminderColors];
                  const IconComponent = reminderIcons[reminder.type as keyof typeof reminderIcons];
                  
                  return (
                    <div key={index} className={`flex items-center justify-between p-3 border rounded-lg ${colors.border} ${colors.bg}`}>
                      <div className="flex items-center space-x-3">
                        <IconComponent className={`h-5 w-5 ${colors.icon}`} />
                        <div>
                          <p className="font-medium">{reminder.title}</p>
                          <p className="text-sm text-neutral-600">{reminder.description}</p>
                        </div>
                      </div>
                      <span className={`text-xs px-2 py-1 rounded ${colors.badge}`}>
                        {reminder.timeframe}
                      </span>
                    </div>
                  );
                });
              })()}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Floating AI Chatbot Button */}
      <div className="fixed bottom-6 right-6 z-40">
        <Button
          onClick={() => setIsChatbotOpen(true)}
          className="w-14 h-14 rounded-full bg-medical-blue hover:bg-blue-700 shadow-lg transition-all duration-300 hover:scale-110"
          size="lg"
        >
          <MessageSquare className="h-6 w-6" />
        </Button>
      </div>

      {/* AI Chatbot */}
      <AIChatbot 
        isOpen={isChatbotOpen} 
        onClose={() => setIsChatbotOpen(false)} 
      />

      {/* Pending Results Popup */}
      <Dialog open={isPendingResultsPopupOpen} onOpenChange={setIsPendingResultsPopupOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-auto">
          <DialogHeader>
            <DialogTitle className="text-xl font-semibold text-gray-900">Pending Results</DialogTitle>
          </DialogHeader>
          
          <div className="space-y-6">
            {pendingResultsData ? (
              <div className="space-y-6">
                {/* Prescriptions */}
                {pendingResultsData.prescriptions && pendingResultsData.prescriptions.length > 0 && (
                  <div>
                    <h3 className="text-lg font-semibold text-gray-800 mb-3 border-b pb-2">Prescriptions ({pendingResultsData.prescriptions.length})</h3>
                    <div className="space-y-3">
                      {pendingResultsData.prescriptions.map((prescription: any, index: number) => (
                        <div key={prescription.id || index} className="border rounded-lg p-4 bg-gray-50">
                          <div className="flex justify-between items-start">
                            <div>
                              <h4 className="font-semibold text-gray-900">{prescription.medicationName}</h4>
                              <p className="text-sm text-gray-600">Dosage: {prescription.dosage}</p>
                              <p className="text-sm text-gray-600">Frequency: {prescription.frequency}</p>
                              <p className="text-sm text-gray-600">Duration: {prescription.duration}</p>
                              {prescription.instructions && (
                                <p className="text-sm text-gray-600">Instructions: {prescription.instructions}</p>
                              )}
                            </div>
                            <span className="px-2 py-1 rounded text-xs bg-yellow-100 text-yellow-800">
                              {prescription.status || 'Pending'}
                            </span>
                          </div>
                          {prescription.issuedDate && (
                            <p className="text-xs text-gray-500 mt-2">
                              Issued: {new Date(prescription.issuedDate).toLocaleDateString()}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Lab Results */}
                {pendingResultsData.labResults && pendingResultsData.labResults.length > 0 && (
                  <div>
                    <h3 className="text-lg font-semibold text-gray-800 mb-3 border-b pb-2">Lab Results ({pendingResultsData.labResults.length})</h3>
                    <div className="space-y-3">
                      {pendingResultsData.labResults.map((labResult: any, index: number) => (
                        <div key={labResult.id || index} className="border rounded-lg p-4 bg-gray-50">
                          <div className="flex justify-between items-start">
                            <div>
                              <h4 className="font-semibold text-gray-900">{labResult.testType}</h4>
                              <p className="text-sm text-gray-600">Test ID: {labResult.testId}</p>
                              <p className="text-sm text-gray-600">Priority: {labResult.priority || 'Routine'}</p>
                              {labResult.doctorName && (
                                <p className="text-sm text-gray-600">Ordered by: {labResult.doctorName}</p>
                              )}
                            </div>
                            <span className="px-2 py-1 rounded text-xs bg-yellow-100 text-yellow-800">
                              {labResult.status || 'Pending'}
                            </span>
                          </div>
                          {labResult.orderedAt && (
                            <p className="text-xs text-gray-500 mt-2">
                              Ordered: {new Date(labResult.orderedAt).toLocaleDateString()}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Medical Records */}
                {pendingResultsData.medicalRecords && pendingResultsData.medicalRecords.length > 0 && (
                  <div>
                    <h3 className="text-lg font-semibold text-gray-800 mb-3 border-b pb-2">Medical Records ({pendingResultsData.medicalRecords.length})</h3>
                    <div className="space-y-3">
                      {pendingResultsData.medicalRecords.map((record: any, index: number) => (
                        <div key={record.id || index} className="border rounded-lg p-4 bg-gray-50">
                          <div className="flex justify-between items-start">
                            <div>
                              <h4 className="font-semibold text-gray-900">{record.title}</h4>
                              <p className="text-sm text-gray-600">Type: {record.type}</p>
                              {record.diagnosis && (
                                <p className="text-sm text-gray-600">Diagnosis: {record.diagnosis}</p>
                              )}
                              {record.notes && (
                                <p className="text-sm text-gray-600 mt-1">{record.notes}</p>
                              )}
                            </div>
                          </div>
                          {record.createdAt && (
                            <p className="text-xs text-gray-500 mt-2">
                              Created: {new Date(record.createdAt).toLocaleDateString()}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* AI Insights */}
                {pendingResultsData.aiInsights && pendingResultsData.aiInsights.length > 0 && (
                  <div>
                    <h3 className="text-lg font-semibold text-gray-800 mb-3 border-b pb-2">AI Insights ({pendingResultsData.aiInsights.length})</h3>
                    <div className="space-y-3">
                      {pendingResultsData.aiInsights.map((insight: any, index: number) => (
                        <div key={insight.id || index} className="border rounded-lg p-4 bg-gray-50">
                          <div className="flex justify-between items-start">
                            <div>
                              <h4 className="font-semibold text-gray-900">{insight.title}</h4>
                              <p className="text-sm text-gray-600">Type: {insight.type}</p>
                              <p className="text-sm text-gray-600">Severity: {insight.severity}</p>
                              <p className="text-sm text-gray-600 mt-1">{insight.description}</p>
                            </div>
                            <span className="px-2 py-1 rounded text-xs bg-yellow-100 text-yellow-800">
                              {insight.aiStatus || 'Pending'}
                            </span>
                          </div>
                          {insight.createdAt && (
                            <p className="text-xs text-gray-500 mt-2">
                              Created: {new Date(insight.createdAt).toLocaleDateString()}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Voice Notes */}
                {pendingResultsData.voiceNotes && pendingResultsData.voiceNotes.length > 0 && (
                  <div>
                    <h3 className="text-lg font-semibold text-gray-800 mb-3 border-b pb-2">Voice Notes ({pendingResultsData.voiceNotes.length})</h3>
                    <div className="space-y-3">
                      {pendingResultsData.voiceNotes.map((voiceNote: any, index: number) => (
                        <div key={voiceNote.id || index} className="border rounded-lg p-4 bg-gray-50">
                          <div className="flex justify-between items-start">
                            <div>
                              <h4 className="font-semibold text-gray-900">{voiceNote.type}</h4>
                              <p className="text-sm text-gray-600">Patient: {voiceNote.patientName}</p>
                              <p className="text-sm text-gray-600">Provider: {voiceNote.providerName}</p>
                              {voiceNote.recordingDuration && (
                                <p className="text-sm text-gray-600">Duration: {voiceNote.recordingDuration}s</p>
                              )}
                            </div>
                            <span className="px-2 py-1 rounded text-xs bg-yellow-100 text-yellow-800">
                              {voiceNote.status || 'Pending'}
                            </span>
                          </div>
                          {voiceNote.createdAt && (
                            <p className="text-xs text-gray-500 mt-2">
                              Created: {new Date(voiceNote.createdAt).toLocaleDateString()}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Claims */}
                {pendingResultsData.claims && pendingResultsData.claims.length > 0 && (
                  <div>
                    <h3 className="text-lg font-semibold text-gray-800 mb-3 border-b pb-2">Claims ({pendingResultsData.claims.length})</h3>
                    <div className="space-y-3">
                      {pendingResultsData.claims.map((claim: any, index: number) => (
                        <div key={claim.id || index} className="border rounded-lg p-4 bg-gray-50">
                          <div className="flex justify-between items-start">
                            <div>
                              <h4 className="font-semibold text-gray-900">Claim #{claim.claimNumber}</h4>
                              <p className="text-sm text-gray-600">Insurance: {claim.insuranceProvider}</p>
                              <p className="text-sm text-gray-600">Amount: {currencySymbol}{claim.amount}</p>
                              <p className="text-sm text-gray-600">Service Date: {new Date(claim.serviceDate).toLocaleDateString()}</p>
                            </div>
                            <span className="px-2 py-1 rounded text-xs bg-yellow-100 text-yellow-800">
                              {claim.status || 'Pending'}
                            </span>
                          </div>
                          {claim.submissionDate && (
                            <p className="text-xs text-gray-500 mt-2">
                              Submitted: {new Date(claim.submissionDate).toLocaleDateString()}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {totalPendingCount === 0 && (
                  <div className="text-center py-8">
                    <FileText className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                    <p className="text-gray-500 text-lg font-medium">No Pending Results</p>
                    <p className="text-gray-400">All your test results and records are up to date.</p>
                  </div>
                )}
              </div>
            ) : (
              <div className="text-center py-8">
                <FileText className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                <p className="text-gray-500 text-lg font-medium">Loading Pending Results...</p>
              </div>
            )}

            <div className="flex justify-end pt-4 border-t">
              <Button 
                variant="outline" 
                onClick={() => setIsPendingResultsPopupOpen(false)}
                className="flex items-center gap-2"
                data-testid="close-pending-results-popup"
              >
                <X className="h-4 w-4" />
                Close
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Prescriptions Popup */}
      <Dialog open={isPrescriptionsPopupOpen} onOpenChange={setIsPrescriptionsPopupOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Pill className="h-5 w-5 text-green-600" />
              Your Active Prescriptions
            </DialogTitle>
          </DialogHeader>
          
          <div className="space-y-4">
            {prescriptionsData && prescriptionsData.prescriptions && prescriptionsData.prescriptions.length > 0 ? (
              prescriptionsData.prescriptions.map((prescription: any) => (
                <Card key={prescription.id} className="border-l-4 border-l-green-500">
                  <CardHeader className="pb-3">
                    <div className="flex justify-between items-start">
                      <div>
                        <CardTitle className="text-lg font-semibold text-gray-900">
                          {prescription.medicationName || 'Unknown Medication'}
                        </CardTitle>
                        <CardDescription className="text-sm text-gray-600">
                          Prescription #{prescription.prescriptionNumber || prescription.id}
                        </CardDescription>
                      </div>
                      <Badge 
                        className={`${prescription.status === 'active' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}
                      >
                        {prescription.status || 'Active'}
                      </Badge>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                      <div>
                        <p className="text-sm font-medium text-gray-500">Dosage</p>
                        <p className="text-sm text-gray-900">{prescription.dosage || 'Not specified'}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-gray-500">Frequency</p>
                        <p className="text-sm text-gray-900">{prescription.frequency || 'Not specified'}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-gray-500">Duration</p>
                        <p className="text-sm text-gray-900">{prescription.duration || 'Not specified'}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-gray-500">Prescribed Date</p>
                        <p className="text-sm text-gray-900">
                          {prescription.issuedDate ? new Date(prescription.issuedDate).toLocaleDateString() : 'N/A'}
                        </p>
                      </div>
                    </div>
                    
                    {prescription.diagnosis && (
                      <div>
                        <p className="text-sm font-medium text-gray-500">Diagnosis</p>
                        <p className="text-sm text-gray-900">{prescription.diagnosis}</p>
                      </div>
                    )}
                    
                    {prescription.instructions && (
                      <div>
                        <p className="text-sm font-medium text-gray-500">Instructions</p>
                        <p className="text-sm text-gray-900">{prescription.instructions}</p>
                      </div>
                    )}

                    {prescription.pharmacy && (
                      <div>
                        <p className="text-sm font-medium text-gray-500">Pharmacy</p>
                        <p className="text-sm text-gray-900">
                          {prescription.pharmacy.name} - {prescription.pharmacy.phone}
                        </p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))
            ) : (
              <div className="text-center py-8">
                <Pill className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                <p className="text-gray-500 text-lg font-medium">No Active Prescriptions</p>
                <p className="text-gray-400 text-sm">You currently have no active prescriptions on file.</p>
              </div>
            )}
          </div>
          
          <div className="flex justify-end pt-4 border-t">
            <Button 
              variant="outline" 
              onClick={() => setIsPrescriptionsPopupOpen(false)}
              className="flex items-center gap-2"
            >
              <X className="h-4 w-4" />
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Lab Results Popup */}
      <Dialog open={isLabResultsPopupOpen} onOpenChange={setIsLabResultsPopupOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-blue-600" />
              Your Lab Results
            </DialogTitle>
          </DialogHeader>
          
          <div className="space-y-4">
            {labResultsData && labResultsData.length > 0 ? (
              labResultsData.map((labResult: any) => (
                <Card key={labResult.id} className="border-l-4 border-l-blue-500" data-testid={`lab-result-card-${labResult.id}`}>
                  <CardHeader className="pb-3">
                    <div className="flex justify-between items-start mb-2">
                      <div>
                        <CardTitle className="text-lg font-semibold text-gray-900">
                          {user?.firstName} {user?.lastName}
                        </CardTitle>
                        <CardDescription className="text-sm text-gray-600">
                          Ordered: {labResult.testDate ? new Date(labResult.testDate).toLocaleDateString() : new Date().toLocaleDateString()} {labResult.testTime || '09:34'}
                        </CardDescription>
                      </div>
                      <Badge 
                        className={`${labResult.status === 'completed' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}`}
                        data-testid={`lab-result-status-${labResult.id}`}
                      >
                        {labResult.status || 'pending'}
                      </Badge>
                    </div>
                    <div className="space-y-2">
                      <div>
                        <p className="text-sm font-medium text-gray-700">Test: <span className="font-normal">{labResult.testType || labResult.type || 'Vitamin D, Thyroid Function Tests'}</span></p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-gray-700">Test ID: <span className="font-normal">{labResult.testId || labResult.id || 'LAB175877489700K5Q18'}</span></p>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div>
                      <h4 className="text-sm font-semibold text-gray-800 mb-2">Notes</h4>
                      <p className="text-sm text-gray-600">{labResult.notes || 'none'}</p>
                    </div>
                    
                    <div className="flex gap-2 pt-3">
                      <Button 
                        variant="outline" 
                        size="sm"
                        className="flex items-center gap-2"
                        onClick={() => {
                          setSelectedLabResult(labResult);
                          setIsLabResultDetailOpen(true);
                        }}
                        data-testid={`view-lab-result-${labResult.id}`}
                      >
                        <FileText className="h-4 w-4" />
                        View Prescription
                      </Button>
                      <Button 
                        variant="outline" 
                        size="sm"
                        className="flex items-center gap-2"
                        onClick={() => generateLabResultPDF(labResult)}
                        data-testid={`download-lab-result-${labResult.id}`}
                      >
                        <Download className="h-4 w-4" />
                        Download PDF
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))
            ) : (
              <div className="text-center py-8">
                <FileText className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                <p className="text-gray-500 text-lg font-medium">No Lab Results</p>
                <p className="text-gray-400 text-sm">You currently have no lab results on file.</p>
              </div>
            )}
          </div>
          
          <div className="flex justify-end pt-4 border-t">
            <Button 
              variant="outline" 
              onClick={() => setIsLabResultsPopupOpen(false)}
              className="flex items-center gap-2"
            >
              <X className="h-4 w-4" />
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Detailed Lab Result Prescription View */}
      <Dialog open={isLabResultDetailOpen} onOpenChange={setIsLabResultDetailOpen}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-center text-xl font-bold">Lab Result Prescription</DialogTitle>
          </DialogHeader>
          
          {selectedLabResult && (
            <div className="space-y-6 p-4">
              {/* Header Section */}
              <div className="text-center space-y-2">
                <div className="flex justify-center items-center gap-3 mb-4">
                  <div className="w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center">
                    <span className="text-white font-bold text-xs">AI</span>
                  </div>
                  <div>
                    <h1 className="text-2xl font-bold text-blue-600">emrSoft System</h1>
                    <p className="text-sm text-gray-600">Laboratory Test Prescription (RESIDENT PHYSICIAN M.D)</p>
                  </div>
                </div>
                <div className="text-sm text-gray-600">
                  <p>EmrSoft Health Clinic</p>
                  <p>Unit 2 Drayton Court, Solihull</p>
                  <p>B90 4NG, UK</p>
                  <p>+92 33***********</p>
                </div>
              </div>

              {/* Information Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Physician Information */}
                <div className="bg-blue-50 p-4 rounded-lg">
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">Physician Information</h3>
                  <div className="space-y-2 text-sm">
                    <div>
                      <span className="font-medium">Name:</span> Dr. Dr. John Smith
                    </div>
                    <div>
                      <span className="font-medium">Main Specialization:</span> General & Primary Care
                    </div>
                    <div>
                      <span className="font-medium">Sub-Specialization:</span> General Practitioner (GP) / Family Physician
                    </div>
                    <div>
                      <span className="font-medium">Priority:</span> routine
                    </div>
                  </div>
                </div>

                {/* Patient Information */}
                <div className="bg-green-50 p-4 rounded-lg">
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">Patient Information</h3>
                  <div className="space-y-2 text-sm">
                    <div>
                      <span className="font-medium">Name:</span> {user?.firstName} {user?.lastName}
                    </div>
                    <div>
                      <span className="font-medium">Patient ID:</span> 25
                    </div>
                    <div>
                      <span className="font-medium">Date:</span> {selectedLabResult.testDate ? new Date(selectedLabResult.testDate).toLocaleDateString() : 'Sep 25, 2025'}
                    </div>
                    <div>
                      <span className="font-medium">Time:</span> {selectedLabResult.testTime || '13:43'}
                    </div>
                  </div>
                </div>
              </div>

              {/* Laboratory Test Prescription Section */}
              <div className="border-t pt-4">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">℞ Laboratory Test Prescription</h3>
                
                <div className="bg-gray-50 p-4 rounded-lg space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm font-medium text-gray-700">Test ID:</p>
                      <p className="text-sm text-gray-900">{selectedLabResult.testId || selectedLabResult.id || 'LAB175877489700K5Q18'}</p>
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-700">Test Type:</p>
                      <p className="text-sm text-blue-600 font-medium">{selectedLabResult.testType || selectedLabResult.type || 'Vitamin D, Thyroid Function Tests'}</p>
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm font-medium text-gray-700">Ordered Date:</p>
                      <p className="text-sm text-gray-900">{selectedLabResult.testDate ? new Date(selectedLabResult.testDate).toLocaleDateString() : 'Sep 25, 2025'} {selectedLabResult.testTime || '09:34'}</p>
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-700">Status:</p>
                      <Badge className={`${selectedLabResult.status === 'completed' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}`}>
                        {selectedLabResult.status || 'PENDING'}
                      </Badge>
                    </div>
                  </div>

                  <div>
                    <p className="text-sm font-medium text-gray-700 mb-2">Clinical Notes:</p>
                    <div className="bg-yellow-50 border-l-4 border-yellow-400 p-3">
                      <p className="text-sm text-gray-900">{selectedLabResult.notes || 'none'}</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex justify-end pt-4 border-t">
                <Button 
                  variant="outline" 
                  onClick={() => setIsLabResultDetailOpen(false)}
                  className="flex items-center gap-2"
                  data-testid="close-lab-result-detail"
                >
                  <X className="h-4 w-4" />
                  Close
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Health Records - Medical Imaging Popup */}
      <Dialog open={isHealthRecordsPopupOpen} onOpenChange={setIsHealthRecordsPopupOpen}>
        <DialogContent className="max-w-6xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold">Medical Imaging</DialogTitle>
            <p className="text-sm text-gray-600">View and manage radiology studies and reports</p>
          </DialogHeader>
          
          <div className="space-y-6 p-4">
            {/* Patient Studies */}
            <div className="space-y-4">
              {medicalImagingData && medicalImagingData.length > 0 ? (
                medicalImagingData.map((imaging: any) => (
                  <Card key={imaging.id} className="border-l-4 border-l-blue-500" data-testid={`imaging-study-${imaging.id}`}>
                    <CardContent className="p-6">
                      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                        {/* Left Column - Patient Info */}
                        <div>
                          <div className="flex items-center gap-2 mb-4">
                            <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs">⚡</div>
                            <h3 className="text-lg font-semibold">{user?.firstName} {user?.lastName}</h3>
                            <Badge className={`${imaging.status === 'completed' ? 'bg-green-100 text-green-800' : 'bg-blue-100 text-blue-800'}`}>
                              {imaging.status || 'completed'}
                            </Badge>
                            <Badge variant="outline">{imaging.priority || 'routine'}</Badge>
                          </div>
                          
                          <div className="space-y-3">
                            <div className="bg-gray-50 p-4 rounded-lg">
                              <h4 className="font-semibold text-gray-900 mb-2">Study Information</h4>
                              <div className="space-y-1 text-sm">
                                <div><span className="font-medium">Study:</span> {imaging.studyType || 'x'}</div>
                                <div><span className="font-medium">Modality:</span> {imaging.modality || 'MRI'}</div>
                                <div><span className="font-medium">Body Part:</span> {imaging.bodyPart || 'dcd'}</div>
                                <div><span className="font-medium">Ordered by:</span> Admin User</div>
                                <div><span className="font-medium">Indication:</span> {imaging.indication || 'none'}</div>
                              </div>
                            </div>
                            
                            <div className="bg-blue-50 p-4 rounded-lg">
                              <h4 className="font-semibold text-gray-900 mb-2">Image Series</h4>
                              <div className="space-y-1 text-sm">
                                <div className="font-medium">{imaging.modality || 'MRI'} {imaging.bodyPart || 'dcd'}</div>
                                <div className="text-gray-600">1 images • {(imaging.fileSize / 1024 / 1024).toFixed(2)} MB • DICOM</div>
                              </div>
                            </div>
                          </div>
                        </div>
                        
                        {/* Right Column - Timeline & Results */}
                        <div>
                          <div className="bg-gray-50 p-4 rounded-lg mb-4">
                            <h4 className="font-semibold text-gray-900 mb-3">Timeline</h4>
                            <div className="space-y-2 text-sm">
                              <div><span className="font-medium">Ordered:</span> {imaging.createdAt ? format(new Date(imaging.createdAt), 'MMM dd, yyyy HH:mm') : 'Sep 25, 2025 09:34'}</div>
                              <div><span className="font-medium">Scheduled:</span> {imaging.scheduledDate ? format(new Date(imaging.scheduledDate), 'MMM dd, yyyy HH:mm') : 'Not scheduled'}</div>
                              <div><span className="font-medium">Performed:</span> {imaging.performedDate ? format(new Date(imaging.performedDate), 'MMM dd, yyyy HH:mm') : 'Not performed'}</div>
                              <div><span className="font-medium">Radiologist:</span> {imaging.radiologist || 'Admin User'}</div>
                            </div>
                          </div>
                          
                          <div className="space-y-4">
                            <div className="bg-blue-50 border-l-4 border-blue-400 p-3">
                              <h4 className="font-semibold text-blue-800 mb-2">Findings</h4>
                              <p className="text-sm text-blue-700">{imaging.findings || 'Medical image uploaded: P000015_Images.png'}</p>
                            </div>
                            
                            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-3">
                              <h4 className="font-semibold text-yellow-800 mb-2">Impression</h4>
                              <p className="text-sm text-yellow-700">File: {imaging.fileName || 'P000015_Images.png'} ({(imaging.fileSize / 1024 / 1024).toFixed(2)} MB)</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))
              ) : (
                <div className="text-center py-8">
                  <Heart className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                  <p className="text-gray-500 text-lg font-medium">No Medical Imaging Studies</p>
                  <p className="text-gray-400">No radiology studies found for this patient.</p>
                </div>
              )}
            </div>

            <div className="flex justify-end pt-4 border-t">
              <Button 
                variant="outline" 
                onClick={() => setIsHealthRecordsPopupOpen(false)}
                className="flex items-center gap-2"
                data-testid="close-health-records-popup"
              >
                <X className="h-4 w-4" />
                Close
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}